window.addEventListener('load',fn,false)
function fn(){setTimeout(()=>{document.getElementById('preloader').style.visibility='hidden';document.getElementById('preloader').style.opacity='0';},350);activateMenu();}
function toggleMenu(){document.getElementById('isToggle').classList.toggle('open');var isOpen=document.getElementById('navigation')
if(isOpen.style.display==="block"){isOpen.style.display="none";}else{isOpen.style.display="block";}};function getClosest(elem,selector){if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||Element.prototype.webkitMatchesSelector||function(s){var matches=(this.document||this.ownerDocument).querySelectorAll(s),i=matches.length;while(--i>=0&&matches.item(i)!==this){}
return i>-1;};}
for(;elem&&elem!==document;elem=elem.parentNode){if(elem.matches(selector))return elem;}
return null;};function activateMenu(){var menuItems=document.getElementsByClassName("sub-menu-item");if(menuItems){var matchingMenuItem=null;for(var idx=0;idx<menuItems.length;idx++){if(menuItems[idx].href===window.location.href){matchingMenuItem=menuItems[idx];}}
if(matchingMenuItem){matchingMenuItem.classList.add('active');var immediateParent=getClosest(matchingMenuItem,'li');if(immediateParent){immediateParent.classList.add('active');}
var parent=getClosest(matchingMenuItem,'.parent-menu-item');if(parent){parent.classList.add('active');var parentMenuitem=parent.querySelector('.menu-item');if(parentMenuitem){parentMenuitem.classList.add('active');}
var parentOfParent=getClosest(parent,'.parent-parent-menu-item');if(parentOfParent){parentOfParent.classList.add('active');}}else{var parentOfParent=getClosest(matchingMenuItem,'.parent-parent-menu-item');if(parentOfParent){parentOfParent.classList.add('active');}}}}}
if(document.getElementById("navigation")){var elements=document.getElementById("navigation").getElementsByTagName("a");for(var i=0,len=elements.length;i<len;i++){elements[i].onclick=function(elem){if(elem.target.getAttribute("href")==="javascript:void(0)"){var submenu=elem.target.nextElementSibling.nextElementSibling;submenu.classList.toggle('open');}}}}
function windowScroll(){const navbar=document.getElementById("topnav");if(navbar!=null){if(document.body.scrollTop>=50||document.documentElement.scrollTop>=50){navbar.classList.add("nav-sticky");}else{navbar.classList.remove("nav-sticky");}}}
window.addEventListener('scroll',(ev)=>{ev.preventDefault();windowScroll();})
feather.replace();try{var spy=new Gumshoe('#navmenu-nav a');}catch(err){}